### ISSUE TITLE
Meaning of the PSI Values

### ISSUE THREAD

**Issue by Cheril184** [biomedical-cybernetics/projection-separability-indices#18]
@aacevedot  @Claudio-dur I would like to know if higher PSI values mean more separability or lower values

**Comment by aacevedot** [comment]
Dear @Cheril184. This depends on whether you are using the projection separability indices (PSIs) we designed and published in our article or implementing a custom index (i.e., yours) based on our projection separability (PS) approach. 

a) If you are using the published PSIs, then the overall interpretation of the values is as follows:

- `PSI-P`: a lower value represents better separability.
- `PSI-ROC`, `PSI-PR`, and `PSI-MCC`: a higher value represents better separability.

b) If you are designing a custom index based on the projection separability (PS) principle, then its interpretation will depend on your underlying statistical approach (if it is either maximized or minimized for separability evaluation over the projection line).

In any case, you can find a detailed explanation of how each PSI was designed and how to design a custom index based on the PS principle in the Methods section of our article [Measuring Group Separability in Geometrical Space for Evaluation of Pattern Recognition and Dimension Reduction Algorithms](https://ieeexplore.ieee.org/document/9716930).

**Comment by aacevedot** [comment]
I hope the meaning of the values is clear now. I am closing this issue.
